Merged local gtk-gnutella modifications in Loc.U back to the dist unit. Regenerated Configure.

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -18,7 +18,7 @@
 
 # $Id$
 #
-# Generated on Sat Jan 22 21:00:35 CET 2011 [metaconfig 3.5-82]
+# Generated on Sat Jan 22 21:55:07 CET 2011 [metaconfig 3.5-84]
 
 cat >c1$$ <<EOF
 ARGGGHHHH!!!!!
@@ -201,6 +201,7 @@ expr=''
 find=''
 flex=''
 gcc=''
+gmake=''
 gmsgfmt=''
 grep=''
 gzip=''
@@ -240,6 +241,7 @@ submit=''
 tail=''
 tar=''
 tbl=''
+tee=''
 test=''
 touch=''
 tr=''
@@ -967,7 +969,7 @@ while test $# -gt 0; do
 	    esac
 	    shift
 	    ;;
-	-V) echo "$me generated by metaconfig 3.5-82." >&2
+	-V) echo "$me generated by metaconfig 3.5-84." >&2
 	    exit 0;;
 	--) break;;
 	-*) echo "$me: unknown option $1" >&2; shift; error=true;;
@@ -1516,6 +1518,24 @@ EOH
 	esac
 fi
 
+: script used to emit important warnings
+cat >warn <<EOS
+$startsh
+if test \$# -gt 0; then
+	echo "\$@" >msg
+else
+	cat >msg
+fi
+echo "*** WARNING:" >&4
+sed -e 's/^/*** /' <msg >&4
+echo "*** " >&4
+cat msg >>config.msg
+echo " " >>config.msg
+rm -f msg
+EOS
+chmod +x warn
+$eunicefix warn
+
 : find out where common programs are
 echo " "
 echo "Locating common programs..." >&4
@@ -1543,9 +1563,16 @@ for dir in \$*; do
 	if test -f \$thisthing; then
 		echo \$thisthing
 		exit 0
+	elif test -f \$thisthing$_exe; then
+		echo \$thisthing
+		exit 0
 	elif test -f \$dir/\$thing.exe; then
-		: on Eunice apparently
-		echo \$dir/\$thing
+		if test -n "$DJGPP"; then
+			echo \$dir/\$thing.exe
+		else
+			: on Eunice apparently
+			echo \$dir/\$thing
+		fi
 		exit 0
 	fi
 	;;
@@ -1603,14 +1630,14 @@ for file in $loclist; do
 		if test -f "$xxx"; then
 			: ok
 		else
-			echo "WARNING: no $xxx -- ignoring your setting for $file." >&4
+			./warn "no $xxx -- ignoring your setting for $file." 4>&4
 			xxx=`./loc $file $file $pth`
 		fi
 		;;
 	'') xxx=`./loc $file $file $pth`;;
 	*) xxx=`./loc $xxx $xxx $pth`;;
 	esac
-	eval $file=$xxx
+	eval $file=$xxx$_exe
 	eval _$file=$xxx
 	case "$xxx" in
 	/*)
@@ -1621,7 +1648,7 @@ for file in $loclist; do
 		;;
 	*)
 		echo "I don't know where '$file' is, and my life depends on it." >&4
-		echo "Go find a free implementation or fix your PATH setting!" >&4
+		echo "Go find a public domain implementation or fix your PATH!" >&4
 		exit 1
 		;;
 	esac
@@ -1636,14 +1663,14 @@ for file in $trylist; do
 		if test -f "$xxx"; then
 			: ok
 		else
-			echo "WARNING: no $xxx -- ignoring your setting for $file." >&4
+			./warn "no $xxx -- ignoring your setting for $file." 4>&4
 			xxx=`./loc $file $file $pth`
 		fi
 		;;
 	'') xxx=`./loc $file $file $pth`;;
 	*) xxx=`./loc $xxx $xxx $pth`;;
 	esac
-	eval $file=$xxx
+	eval $file=$xxx$_exe
 	eval _$file=$xxx
 	case "$xxx" in
 	/*)
@@ -1662,12 +1689,36 @@ case "$egrep" in
 egrep)
 	echo "Substituting grep for egrep."
 	egrep=$grep
+	_egrep=$_grep
 	;;
 esac
 case "$ln" in
 ln)
 	echo "Substituting cp for ln."
 	ln=$cp
+	_ln=$_cp
+	;;
+esac
+case "$make" in
+make)	
+	case "$gmake" in
+	gmake)
+	echo "I can't find make or gmake, and my life depends on it." >&4
+	echo "Go find a public domain implementation or fix your PATH setting!" >&4
+	exit 1
+	;;
+	esac
+	;;
+esac	
+case "$gmake" in
+gmake)	;;
+*)
+	if test -f "/system/gnu_library/bin/ar.pm"; then
+		: Stratus VOS
+		echo "Substituting gmake for make."
+		make=$gmake
+		_make=$_gmake
+	fi
 	;;
 esac
 case "$gmsgfmt" in
@@ -1704,9 +1755,9 @@ xgettext)
 	elif $xgettext --from-code=UTF-8 /dev/null >/dev/null 2>&1; then
 		: ok
 	else
-		echo "Your $xgettext does not support --from-code; ignoring it."
-		xgettext=":"
-		_xgettext=":"
+		 echo "Your $xgettext does not support --from-code; ignoring it."
+		 xgettext=":"
+		 _xgettext=":"
 	fi
 	;;
 esac
@@ -1752,24 +1803,6 @@ FOO
 	$rm -f foo1 foo2
 	;;
 esac
-
-: script used to emit important warnings
-cat >warn <<EOS
-$startsh
-if test \$# -gt 0; then
-	echo "\$@" >msg
-else
-	cat >msg
-fi
-echo "*** WARNING:" >&4
-sed -e 's/^/*** /' <msg >&4
-echo "*** " >&4
-cat msg >>config.msg
-echo " " >>config.msg
-rm -f msg
-EOS
-chmod +x warn
-$eunicefix warn
 
 : generate the trygcc script for later perusal
 cat <<EOS >trygcc
@@ -2379,7 +2412,6 @@ case "$knowitall" in
 *) dflt=y;;
 esac
 
-saved_myuname="$myuname"
 saved_osname="$osname"
 saved_osvers="$osvers"
 
@@ -2433,7 +2465,6 @@ $test "$override" && . ./optdef.sh
 for file in $loclist $trylist; do
 	eval $file="\$_$file"
 done
-myuname="$saved_myuname"
 osname="$saved_osname"
 osvers="$saved_osvers"
 
@@ -10016,6 +10047,7 @@ glibldflags='$glibldflags'
 glibpackage='$glibpackage'
 glibpth='$glibpth'
 glibversion='$glibversion'
+gmake='$gmake'
 gmsgfmt='$gmsgfmt'
 gnulibc_version='$gnulibc_version'
 gnutlscflags='$gnutlscflags'
@@ -10215,6 +10247,7 @@ tail='$tail'
 tar='$tar'
 targetarch='$targetarch'
 tbl='$tbl'
+tee='$tee'
 test='$test'
 timeincl='$timeincl'
 to='$to'
