Regenerated.

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -18,7 +18,7 @@
 
 # $Id$
 #
-# Generated on Sun Jan 30 23:36:38 CET 2011 [metaconfig 3.5-91]
+# Generated on Mon Feb  7 04:06:29 CET 2011 [metaconfig 3.5-]
 
 cat >c1$$ <<EOF
 ARGGGHHHH!!!!!
@@ -970,7 +970,7 @@ while test $# -gt 0; do
 	    esac
 	    shift
 	    ;;
-	-V) echo "$me generated by metaconfig 3.5-91." >&2
+	-V) echo "$me generated by metaconfig 3.5-." >&2
 	    exit 0;;
 	--) break;;
 	-*) echo "$me: unknown option $1" >&2; shift; error=true;;
@@ -5031,7 +5031,7 @@ esac
 case "$usesocks" in
 "$define") libswanted="$libswanted socks5 socks5_sh" ;;
 esac
-echo "extern char printf(); int main() { printf(); return 0; }" > lt.c
+echo "extern void abort(void); int main(void) { abort(); return 0; }" > lt.c
 libsfound=''
 libsfiles=''
 libsdirs=''
