No longer rely on glib's determination of the byte ordering.
Taught Configure about float byte-ordering as well and make sure we behave
correctly on platforms where it differs from the one used for integer.

No longer need to hardwire the list of platforms supporting IEEE 754 floats
now that Configure can detect their support.

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -18,7 +18,7 @@
 
 # $Id: Head.U 41 2010-11-28 00:21:26Z rmanfredi $
 #
-# Generated on Sat Feb  4 07:27:24 CET 2012 [metaconfig 3.5-119]
+# Generated on Wed Feb  8 17:03:20 RST 2012 [metaconfig 3.5-128]
 
 cat >c1$$ <<EOF
 ARGGGHHHH!!!!!
@@ -250,6 +250,7 @@ uname=''
 uniq=''
 uuname=''
 vi=''
+wc=''
 xgettext=''
 zcat=''
 zip=''
@@ -286,6 +287,7 @@ myarchname=''
 bin=''
 binexp=''
 installbin=''
+byteorder=''
 cc=''
 ccflags=''
 cppflags=''
@@ -343,6 +345,8 @@ d_headless=''
 d_herror=''
 d_hstrerror=''
 d_iconv=''
+d_ieee754=''
+ieee754_byteorder=''
 d_inflate=''
 d_iptos=''
 d_ipv6=''
@@ -977,7 +981,7 @@ while test $# -gt 0; do
 	    esac
 	    shift
 	    ;;
-	-V) echo "$me generated by metaconfig 3.5-119." >&2
+	-V) echo "$me generated by metaconfig 3.5-128." >&2
 	    exit 0;;
 	--) break;;
 	-*) echo "$me: unknown option $1" >&2; shift; error=true;;
@@ -1154,6 +1158,7 @@ esac
 cat >extract <<EOS
 CONFIG=true
 SRC="$src"
+TOP=`cd ..; pwd 2>/dev/null`
 EOS
 cat >>extract <<'EOS'
 echo "Doing variable substitutions on .SH files..."
@@ -1627,6 +1632,7 @@ nm
 nroff
 test
 uname
+wc
 xgettext
 "
 pth=`echo $PATH | sed -e "s/$p_/ /g"`
@@ -1645,7 +1651,7 @@ for file in $loclist; do
 	'') xxx=`./loc $file $file $pth`;;
 	*) xxx=`./loc $xxx $xxx $pth`;;
 	esac
-	eval $file=$xxx$_exe
+	eval $file=$xxx
 	eval _$file=$xxx
 	case "$xxx" in
 	/*)
@@ -1678,7 +1684,7 @@ for file in $trylist; do
 	'') xxx=`./loc $file $file $pth`;;
 	*) xxx=`./loc $xxx $xxx $pth`;;
 	esac
-	eval $file=$xxx$_exe
+	eval $file=$xxx
 	eval _$file=$xxx
 	case "$xxx" in
 	/*)
@@ -1694,21 +1700,21 @@ for file in $trylist; do
 	esac
 done
 case "$egrep" in
-egrep$_exe)
+egrep$_exe|egrep)
 	echo "Substituting grep for egrep."
 	egrep=$grep
 	_egrep=$_grep
 	;;
 esac
 case "$ln" in
-ln$_exe)
+ln$_exe|ln)
 	echo "Substituting cp for ln."
 	ln=$cp
 	_ln=$_cp
 	;;
 esac
 case "$make" in
-make$_exe)	
+make$_exe|make)	
 	case "$gmake" in
 	gmake)
 	echo "I can't find make or gmake, and my life depends on it." >&4
@@ -1719,7 +1725,7 @@ make$_exe)
 	;;
 esac	
 case "$gmake" in
-gmake$_exe)	;;
+gmake$_exe|gmake)	;;
 *)
 	if test -f "/system/gnu_library/bin/ar.pm"; then
 		: Stratus VOS
@@ -1730,7 +1736,7 @@ gmake$_exe)	;;
 	;;
 esac
 case "$gmsgfmt" in
-gmsgfmt$_exe)
+gmsgfmt$_exe|gmsgfmt)
 	echo "Substituting msgfmt for gmsgfmt."
 	gmsgfmt=$msgfmt
 	_gmsgfmt=$_msgfmt
@@ -1747,7 +1753,7 @@ gmsgfmt$_exe)
 	;;
 esac
 case "$xgettext" in
-xgettext$_exe)
+xgettext$_exe|xgettext)
 	xgettext=":"
 	_xgettext=":"
 	;;
@@ -2480,7 +2486,7 @@ $test "$override" && . ./optdef.sh
 
 : Restore computed paths
 for file in $loclist $trylist; do
-	eval $file="\$_$file"$_exe
+	eval $file="\$_$file"
 done
 
 osname="$saved_osname"
@@ -5890,6 +5896,38 @@ cyn=hstrerror
 set d_hstrerror 
 eval $trylink
 
+: check for ieee754 float and their endianness
+echo " "
+$echo $n "Checking IEEE-754 float byte-ordering...$c" >&4
+$cat >try.c <<'EOCP'
+float ascii_le[] = {
+	3223.213134765625, 6.8273612896518898e-07, 1.9753562586009612e+31, 0 };
+float ascii_be[] = {
+	865942.3125, 6.7652519659605424e+22, 1.9695089292781631e-07, 0 };
+EOCP
+order=0
+val=''
+if $cc -c $ccflags try.c >/dev/null 2>&1; then
+	if $contains ISieee754Sys try$_o >/dev/null 2>&1; then
+		val=$define
+		order=4321
+	elif $contains isIEEE754Sys try$_o >/dev/null 2>&1; then
+		val=$define
+		order=1234
+	else
+		val=$undef
+	fi
+fi
+set d_ieee754
+eval $setvar
+case "$order" in
+0)    echo " not using IEEE-754 here." >&4;;
+1234) echo " little-endian." >&4;;
+4321) echo " big-endian." >&4;;
+esac
+ieee754_byteorder=$order
+$rm -f try.c try$_o
+
 : index or strchr
 $cat >try.c <<EOC
 #include <string.h>
@@ -7739,6 +7777,46 @@ rp="What is the maximum alignment in bytes required for a standard type?"
 . ./myread
 alignbytes="$ans"
 
+: check for ordering of bytes in a word
+echo " "
+$echo $n "Checking integer byte-ordering...$c" >&4
+$cat >try.c <<'EOCP'
+short ascii_be[] = { 0x4249, 0x4765, 0x6E44, 0x6961, 0x6E53, 0x7953, 0 };
+short ascii_le[] = { 0x694C, 0x5454, 0x656C, 0x6E45, 0x6944, 0x6E61, 0 };
+short ebcdic_be[] = { 0xC2C9, 0xC785, 0x95C4, 0x8981, 0x95E2, 0xA8E2, 0 };
+short ebcdic_le[] = { 0x89D3, 0xE3E3, 0x8593, 0x95C5, 0x89C4, 0x9581, 0 };
+EOCP
+order=''
+if $cc -c $ccflags try.c >/dev/null 2>&1; then
+	if $contains BIGenDianSyS try$_o >/dev/null 2>&1; then
+		order=4321
+	elif $contains LiTTleEnDian try$_o >/dev/null 2>&1; then
+		order=1234
+	else
+		$echo $n " wild guessing$c" >&4
+		order=4321
+	fi
+fi
+case "$order" in
+'')
+	echo " cannot compute it." >&4
+	rp="Are integers stored in big-endian format?"
+	case "$byteorder" in
+	1234) dflt=n;;
+	*) dflt=y;;
+	esac
+	. ./myread
+	case "$ans" in
+	y*) order=4321;;
+	*)	order=1234;;
+	esac
+	;;
+1234) echo " little-endian." >&4;;
+4321) echo " big-endian." >&4;;
+esac
+byteorder=$order
+$rm -f try.c try$_o
+
 : how do we catenate cpp tokens here?
 echo " "
 echo "Checking to see how your cpp does stuff like catenate tokens..." >&4
@@ -8299,7 +8377,12 @@ EOS
 			creatdir="$prog -d"
 		fi
 		(ls -l d/try >try.ls; ls -l d/try.ns >tryno.ls) 2>/dev/null
-		if (cmp -s d/try try && cmp -s d/try.ns try.ns && \
+		try_wc=`($wc -c try | $awk '{ print $1}') 2>/dev/null`
+		tryns_wc=`($wc -c try.ns | $awk '{ print $1}') 2>/dev/null`
+		d_try_wc=`($wc -c d/try | $awk '{ print $1}') 2>/dev/null`
+		d_tryns_wc=`($wc -c d/try.ns | $awk '{ print $1}') 2>/dev/null`
+		if ($test "X$try_wc" = "X$d_try_wc" && \
+			$test "X$tryns_wc" = "X$d_tryns_wc" && \
 			$contains 'rwxrw-r--' tryno.ls && \
 			$contains 'rw-r---w-' try.ls) >/dev/null 2>&1
 		then
@@ -10039,6 +10122,7 @@ bin='$bin'
 binexp='$binexp'
 bison='$bison'
 byacc='$byacc'
+byteorder='$byteorder'
 c='$c'
 cat='$cat'
 cc='$cc'
@@ -10112,6 +10196,7 @@ d_headless='$d_headless'
 d_herror='$d_herror'
 d_hstrerror='$d_hstrerror'
 d_iconv='$d_iconv'
+d_ieee754='$d_ieee754'
 d_index='$d_index'
 d_inflate='$d_inflate'
 d_iptos='$d_iptos'
@@ -10298,6 +10383,7 @@ i_varhdr='$i_varhdr'
 i_winsock2='$i_winsock2'
 i_ws2tcpip='$i_ws2tcpip'
 i_zlib='$i_zlib'
+ieee754_byteorder='$ieee754_byteorder'
 incpath='$incpath'
 inews='$inews'
 install='$install'
@@ -10437,6 +10523,7 @@ usrinc='$usrinc'
 uuname='$uuname'
 vi='$vi'
 voidflags='$voidflags'
+wc='$wc'
 xgettext='$xgettext'
 xlibpth='$xlibpth'
 yacc='$yacc'
