Override metaconfig's mallocsrc.U to always use our malloc() by default.
The standard metaconfig unit does not offer to use the local malloc() on
64-bit platforms.  Since gtk-gnutella's malloc() has now been extensively
tested on such platforms, it is deemed to be perfectly safe to use and can
therefore be compiled in by default.

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -18,7 +18,7 @@
 
 # $Id: Head.U 167 2013-05-08 17:58:00Z rmanfredi $
 #
-# Generated on Fri Sep  6 14:01:38 CEST 2013 [metaconfig 3.5-171]
+# Generated on Sat Nov  2 10:52:09 CET 2013 [metaconfig 3.5-172]
 
 cat >c1$$ <<EOF
 ARGGGHHHH!!!!!
@@ -1030,7 +1030,7 @@ while test $# -gt 0; do
 	    esac
 	    shift
 	    ;;
-	-V) echo "$me generated by metaconfig 3.5-171." >&2
+	-V) echo "$me generated by metaconfig 3.5-172." >&2
 	    exit 0;;
 	--) break;;
 	-*) echo "$me: unknown option $1" >&2; shift; error=true;;
@@ -4210,53 +4210,12 @@ none) libs=' ';;
 *) libs="$ans";;
 esac
 
-: static assertion checking include file
-$cat >static_assert.h <<'EOC'
-#define STATIC_ASSERT(expr)	\
-	do { switch (0) { case ((expr) ? 1 : 0): case 0: break; } } while(0)
-EOC
-
-: check for length of pointer
-echo " "
-$echo $n "Checking to see how big your pointers are...$c" >&4
-for size in 2 4 8 16 error; do
-	$cat >try.c <<EOCP
-#include "static_assert.h"
-char *foo;
-int main()
-{
-	STATIC_ASSERT($size == sizeof(foo));
-	return 0;
-}
-EOCP
-	if $cc -c $ccflags try.c >/dev/null 2>&1; then break; fi
-done
-case "$size" in
-error)
-	echo " cannot compute it." >&4
-	dflt=4
-	rp="What is the size of a pointer type (in bytes)?"
-	. ./myread
-	ptrsize="$ans"
-	;;
-*)
-	echo " $size bytes." >&4
-	ptrsize=$size
-	;;
-esac
-$rm -f try.*
-
 : determine which malloc to compile in
 echo " "
 case "$usemymalloc" in
 [yY]*|true|$define) dflt='y' ;;
 [nN]*|false|$undef) dflt='n' ;;
-*)
-	case "$ptrsize" in
-	4) dflt='y' ;;
-	*) dflt='n' ;;
-	esac
-	;;
+*) dflt=y ;;
 esac
 $cat <<EOM
 $spackage comes with its own malloc() implementation that will supersede
@@ -4978,6 +4937,12 @@ cyn=bzero
 set d_bzero
 eval $trylink
 
+: static assertion checking include file
+$cat >static_assert.h <<'EOC'
+#define STATIC_ASSERT(expr)	\
+	do { switch (0) { case ((expr) ? 1 : 0): case 0: break; } } while(0)
+EOC
+
 : check for lengths of integral types
 echo " "
 types=''
@@ -5017,6 +4982,36 @@ EOCP
 		;;
 	esac
 done
+$rm -f try.*
+
+: check for length of pointer
+echo " "
+$echo $n "Checking to see how big your pointers are...$c" >&4
+for size in 2 4 8 16 error; do
+	$cat >try.c <<EOCP
+#include "static_assert.h"
+char *foo;
+int main()
+{
+	STATIC_ASSERT($size == sizeof(foo));
+	return 0;
+}
+EOCP
+	if $cc -c $ccflags try.c >/dev/null 2>&1; then break; fi
+done
+case "$size" in
+error)
+	echo " cannot compute it." >&4
+	dflt=4
+	rp="What is the size of a pointer type (in bytes)?"
+	. ./myread
+	ptrsize="$ans"
+	;;
+*)
+	echo " $size bytes." >&4
+	ptrsize=$size
+	;;
+esac
 $rm -f try.*
 
 : check for architecture type
