Jumbo type sanitization patch: remove all glib types everywhere but in the GUI.

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -18,7 +18,7 @@
 
 # $Id: Head.U 41 2010-11-28 00:21:26Z rmanfredi $
 #
-# Generated on Wed Feb  8 17:03:20 RST 2012 [metaconfig 3.5-128]
+# Generated on Fri Feb 10 16:57:40 RST 2012 [metaconfig 3.5-135]
 
 cat >c1$$ <<EOF
 ARGGGHHHH!!!!!
@@ -297,6 +297,7 @@ locincpth=''
 optimize=''
 cf_by=''
 cf_time=''
+charsize=''
 contains=''
 cpp_quote=''
 cpp_stuff=''
@@ -515,8 +516,16 @@ i_varhdr=''
 i_winsock2=''
 i_ws2tcpip=''
 i_zlib=''
+d_can64=''
+d_ilp32=''
+d_ilp64=''
+d_lp64=''
+ilp=''
 install=''
 installdir=''
+intsize=''
+longsize=''
+shortsize=''
 issymlink=''
 libc=''
 libnames=''
@@ -572,6 +581,7 @@ installprivlib=''
 privlib=''
 privlibexp=''
 prototype=''
+ptrsize=''
 d_remotectrl=''
 remotectrl=''
 sh=''
@@ -981,7 +991,7 @@ while test $# -gt 0; do
 	    esac
 	    shift
 	    ;;
-	-V) echo "$me generated by metaconfig 3.5-128." >&2
+	-V) echo "$me generated by metaconfig 3.5-135." >&2
 	    exit 0;;
 	--) break;;
 	-*) echo "$me: unknown option $1" >&2; shift; error=true;;
@@ -4128,6 +4138,7 @@ case "$cyn" in
 esac;
 $cat try.c >> "$file";
 while :; do
+	$rm -f try$_exe;
 	if $cc $ccflags -o try try.c $ldflags $1 >> "$file" 2>&1; then
 		case "$nparams" in 0) ;; *) echo "==> OK with \"$1\"" >> "$file";; esac;
 		val=$define;
@@ -4585,6 +4596,141 @@ EOC
 cyn=bzero
 set d_bzero
 eval $trylink
+
+: static assertion checking include file
+$cat >static_assert.h <<'EOC'
+#define STATIC_ASSERT(expr)	\
+	do { switch (0) { case ((expr) ? 1 : 0): case 0: break; } } while(0)
+EOC
+
+: check for lengths of integral types
+echo " "
+types=''
+types="$types short"
+types="$types int"
+types="$types long"
+for t in $types; do
+	$echo $n "Checking to see how big your ${t}s are...$c" >&4
+	for size in 2 4 8 16 error; do
+		$cat >try.c <<EOCP
+#include "static_assert.h"
+$t foo;
+int main()
+{
+	STATIC_ASSERT($size == sizeof(foo));
+	return 0;
+}
+EOCP
+		if $cc -c $ccflags try.c >/dev/null 2>&1; then break; fi
+	done
+	var=${t}size
+	case "$size" in
+	error)
+		echo " cannot compute it." >&4
+		case $t in
+		short) dflt=2;;
+		int) dflt=4;;
+		long) dflt=4;;
+		esac
+		rp="What is the size of the \"$t\" type (in bytes)?"
+		. ./myread
+		eval $var="$ans"
+		;;
+	*)
+		echo " $size bytes." >&4
+		eval $var=$size
+		;;
+	esac
+done
+$rm -f try.*
+
+: check for length of pointer
+echo " "
+$echo $n "Checking to see how big your pointers are...$c" >&4
+for size in 2 4 8 16 error; do
+	$cat >try.c <<EOCP
+#include "static_assert.h"
+char *foo;
+int main()
+{
+	STATIC_ASSERT($size == sizeof(foo));
+	return 0;
+}
+EOCP
+	if $cc -c $ccflags try.c >/dev/null 2>&1; then break; fi
+done
+case "$size" in
+error)
+	echo " cannot compute it." >&4
+	dflt=4
+	rp="What is the size of a pointer type (in bytes)?"
+	. ./myread
+	ptrsize="$ans"
+	;;
+*)
+	echo " $size bytes." >&4
+	ptrsize=$size
+	;;
+esac
+$rm -f try.*
+
+: check for architecture type
+echo " "
+$echo $n "Computing CPU architecture type...$c" >&4
+ilp=`expr $longsize \* 8`
+case "$ptrsize" in
+8)
+	val=$undef; set d_ilp32; eval $setvar
+	case "$intsize" in
+	8)	
+		echo " ILP64." >&4
+		val=$define; set d_ilp64; eval $setvar
+		val=$undef; set d_lp64; eval $setvar
+		;;
+	*)
+		echo " LP64." >&4
+		val=$define; set d_lp64; eval $setvar
+		val=$undef; set d_ilp64; eval $setvar
+		;;
+	esac
+	;;
+*)
+	echo " ILP${ilp}." >&4
+	case "$ilp" in
+	32) val=$define;;
+	*) val=$undef;;
+	esac
+	set d_ilp32; eval $setvar
+	val=$undef; set d_ilp64; eval $setvar
+	val=$undef; set d_lp64; eval $setvar
+	;;
+esac
+
+: see whether compiler supports 64-bit emulation
+case "$ilp" in
+64) ;;
+*)
+	$cat >try.c <<EOCP
+#include "static_assert.h"
+long long foo;
+int main()
+{
+	STATIC_ASSERT(8 == sizeof(foo));
+	return 0;
+}
+EOCP
+	if $cc -c $ccflags try.c >/dev/null 2>&1; then
+		echo " "
+		echo "Your compiler also supports 64-bit emulation." >&4
+		val=$define
+	else
+		val=$undef
+	fi
+	set d_can64
+	eval $setvar
+	$rm -f try.*
+	;;
+esac
 
 : can we use closefrom?
 $cat >try.c <<EOC
@@ -6053,13 +6199,12 @@ case "$d_ipv6" in
 #include <netdb.h>
 #endif
 #ifdef I_WINSOCK2
-#include "Winsock2.h"
+#include <Winsock2.h>
 #endif
 #ifdef I_WS2TCPIP
-#include "Ws2tcpip.h"
+#include <Ws2tcpip.h>
 #endif
-#define STATIC_ASSERT(x)	\
-	do { switch (0) { case ((x) ? 1 : 0): case 0: break; } } while(0)
+#include "static_assert.h"
 
 int main(void)
 {
@@ -7743,8 +7888,7 @@ struct s {
 	union u b;
 };
 
-#define STATIC_ASSERT(expr)	\
-	do { switch (0) { case ((expr) ? 1 : 0): case 0: break; } } while(0)
+#include "static_assert.h"
 
 int
 main(void)
@@ -7816,6 +7960,40 @@ case "$order" in
 esac
 byteorder=$order
 $rm -f try.c try$_o
+
+: check for length of character
+echo " "
+$echo $n "Checking to see how big your characters are...$c" >&4
+for size in 1 2 4 8 error; do
+	$cat >try.c <<EOCP
+#include "static_assert.h"
+char foo;
+int main()
+{
+	STATIC_ASSERT($size == sizeof(foo));
+	return 0;
+}
+EOCP
+	if $cc -c $ccflags try.c >/dev/null 2>&1; then break; fi
+done
+case "$size" in
+error)
+	echo " cannot compute it." >&4
+	dflt=1
+	rp="What is the size of a character (in bytes)?"
+	. ./myread
+	charsize="$ans"
+	;;
+*)
+	case "$size" in
+	1) s='';;
+	*) s='s';;
+	esac
+	echo " $size byte$s." >&4
+	charsize=$size
+	;;
+esac
+$rm -f try.*
 
 : how do we catenate cpp tokens here?
 echo " "
@@ -10131,6 +10309,7 @@ ccname='$ccname'
 ccversion='$ccversion'
 cf_by='$cf_by'
 cf_time='$cf_time'
+charsize='$charsize'
 chgrp='$chgrp'
 chmod='$chmod'
 chown='$chown'
@@ -10162,6 +10341,7 @@ d_bindtxtcode='$d_bindtxtcode'
 d_bsd='$d_bsd'
 d_built_popcount='$d_built_popcount'
 d_bzero='$d_bzero'
+d_can64='$d_can64'
 d_closefrom='$d_closefrom'
 d_const='$d_const'
 d_dbus='$d_dbus'
@@ -10197,6 +10377,8 @@ d_herror='$d_herror'
 d_hstrerror='$d_hstrerror'
 d_iconv='$d_iconv'
 d_ieee754='$d_ieee754'
+d_ilp32='$d_ilp32'
+d_ilp64='$d_ilp64'
 d_index='$d_index'
 d_inflate='$d_inflate'
 d_iptos='$d_iptos'
@@ -10206,6 +10388,7 @@ d_kevent_int_udata='$d_kevent_int_udata'
 d_kqueue='$d_kqueue'
 d_linux='$d_linux'
 d_locale_charset='$d_locale_charset'
+d_lp64='$d_lp64'
 d_lstat='$d_lstat'
 d_madvise='$d_madvise'
 d_memalign='$d_memalign'
@@ -10384,6 +10567,7 @@ i_winsock2='$i_winsock2'
 i_ws2tcpip='$i_ws2tcpip'
 i_zlib='$i_zlib'
 ieee754_byteorder='$ieee754_byteorder'
+ilp='$ilp'
 incpath='$incpath'
 inews='$inews'
 install='$install'
@@ -10392,6 +10576,7 @@ installbin='$installbin'
 installdir='$installdir'
 installmansrc='$installmansrc'
 installprivlib='$installprivlib'
+intsize='$intsize'
 issymlink='$issymlink'
 ksh='$ksh'
 large='$large'
@@ -10416,6 +10601,7 @@ locale='$locale'
 localeexp='$localeexp'
 locincpth='$locincpth'
 loclibpth='$loclibpth'
+longsize='$longsize'
 lp='$lp'
 lpr='$lpr'
 ls='$ls'
@@ -10467,6 +10653,7 @@ prefixexp='$prefixexp'
 privlib='$privlib'
 privlibexp='$privlibexp'
 prototype='$prototype'
+ptrsize='$ptrsize'
 ranlib='$ranlib'
 rd_nodata='$rd_nodata'
 remotectrl='$remotectrl'
@@ -10479,6 +10666,7 @@ sendmail='$sendmail'
 sh='$sh'
 shar='$shar'
 sharpbang='$sharpbang'
+shortsize='$shortsize'
 shsharp='$shsharp'
 sig_count='$sig_count'
 sig_name='$sig_name'
