We now need GnuTLS 2.2.5 at least to compile.

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -18,7 +18,7 @@
 
 # $Id$
 #
-# Generated on Mon Feb  7 04:06:29 CET 2011 [metaconfig 3.5-]
+# Generated on Mon Feb  7 14:10:07 CET 2011 [metaconfig 3.5-93]
 
 cat >c1$$ <<EOF
 ARGGGHHHH!!!!!
@@ -970,7 +970,7 @@ while test $# -gt 0; do
 	    esac
 	    shift
 	    ;;
-	-V) echo "$me generated by metaconfig 3.5-." >&2
+	-V) echo "$me generated by metaconfig 3.5-93." >&2
 	    exit 0;;
 	--) break;;
 	-*) echo "$me: unknown option $1" >&2; shift; error=true;;
@@ -5741,8 +5741,8 @@ case "$version" in
 '') ;;
 *)
 	vint=`echo $version | $awk -F. '{print $1 * 10000 + $2 * 100 + $3;}'`
-	if test 0$vint -lt 010016; then
-		echo "Sorry, you have GnuTLS $version, I need at least 1.0.16." >&4
+	if test 0$vint -lt 020205; then
+		echo "Sorry, you have GnuTLS $version, I need at least 2.2.5." >&4
 	else
 		echo "Good, you have GnuTLS $version." >&4
 		
@@ -6738,26 +6738,27 @@ int main(void)
 	return 1;
 }
 EOP
-	if $cc $ccflags $ldflags -o set set.c $libs; then
+	if $cc $ccflags $ldflags -o set set.c $libs >/dev/null 2>&1; then
 		if ./set >/dev/null 2>&1; then
-			echo "POSIX sigsetjmp found." >&4
+			echo "POSIX sigsetjmp() found." >&4
 			val="$define"
 		else
 			$cat >&4 <<EOM
-Uh-Oh! You have POSIX sigsetjmp and siglongjmp, but they do not work properly!!
+Uh-Oh!
+You have POSIX sigsetjmp() and siglongjmp(), but they do not work properly!!
 I'll ignore them.
 EOM
 			val="$undef"
 		fi
 	else
-		echo "sigsetjmp not found." >&4
+		echo "sigsetjmp() not found." >&4
 		val="$undef"
 	fi
 	;;
 *) val="$d_sigsetjmp"
 	case "$d_sigsetjmp" in
-	$define) echo "POSIX sigsetjmp found." >&4;;
-	$undef) echo "sigsetjmp not found." >&4;;
+	$define) echo "POSIX sigsetjmp() found." >&4;;
+	$undef) echo "sigsetjmp() not found." >&4;;
 	esac
 	;;
 esac
