* Hopefully fixed Configure's option parsing. Didn't really test the -A stuff.

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -713,75 +713,6 @@ config_arg0='$0'
 config_args='$*'
 config_argc=$#
 EOSH
-argn=1
-args_exp=''
-args_sep=''
-for arg in "$@"; do
-	cat >>cmdline.opt <<EOSH
-config_arg$argn='$arg'
-EOSH
-	cat <<EOC | sed -e "s/'/'"'"'"'"'"'"'/g" > cmdl.opt
-$arg
-EOC
-	arg_exp=`cat cmdl.opt`
-	args_exp="$args_exp$args_sep'$arg_exp'"
-	argn=`expr $argn + 1`
-	args_sep=' '
-done
-rm -f cmdl.opt
-
-: produce awk script to parse command line options
-cat >options.awk <<'EOF'
-BEGIN {
-	optstr = "A:dD:eEf:hKOrsSU:V";	# getopt-style specification
-
-	len = length(optstr);
-	for (i = 1; i <= len; i++) {
-		c = substr(optstr, i, 1);
-		if (i < len) a = substr(optstr, i + 1, 1); else a = "";
-		if (a == ":") {
-			arg[c] = 1;
-			i++;
-		}
-		opt[c] = 1;
-	}
-}
-{
-	expect = 0;
-	str = $0;
-	if (substr(str, 1, 1) != "-") {
-		printf("'%s'\n", str);
-		next;
-	}
-	len = length($0);
-	for (i = 2; i <= len; i++) {
-		c = substr(str, i, 1);
-		if (!opt[c]) {
-			printf("-%s\n", substr(str, i));
-			next;
-		}
-		printf("-%s\n", c);
-		if (arg[c]) {
-			if (i < len)
-				printf("'%s'\n", substr(str, i + 1));
-			else
-				expect = 1;
-			next;
-		}
-	}
-}
-END {
-	if (expect)
-		print "?";
-}
-EOF
-
-: process the command line options
-set X `for arg in "$@"; do echo "X$arg"; done |
-	sed -e s/X// | awk -f options.awk`
-eval "set $*"
-shift
-rm -f options.awk
 
 : set up default values
 fastread=''
@@ -801,108 +732,164 @@ EOS
 
 : option parsing
 while test $# -gt 0; do
-	case "$1" in
-	-d) shift; fastread=yes;;
-	-e) shift; alldone=cont;;
-	-f)
-		shift
-		cd ..
-		if test -r "$1"; then
-			config_sh="$1"
-		else
-			echo "$me: cannot read config file $1." >&2
-			error=true
-		fi
-		cd UU
-		shift;;
-	-h) shift; error=true;;
-	-r) shift; reuseval=true;;
-	-s) shift; silent=true; realsilent=true;;
-	-E) shift; alldone=exit;;
-	-K) shift; knowitall=true;;
-	-O) shift; override=true;;
-	-S) shift; silent=true; extractsh=true;;
-	-D)
-		shift
-		case "$1" in
-		*=)
-			echo "$me: use '-U symbol=', not '-D symbol='." >&2
-			echo "$me: ignoring -D $1" >&2
-			;;
-		*=*) echo "$1" | \
-				sed -e "s/'/'\"'\"'/g" -e "s/=\(.*\)/='\1'/" >> optdef.sh;;
-		*) echo "$1='define'" >> optdef.sh;;
-		esac
-		shift
-		;;
-	-U)
-		shift
-		case "$1" in
-		*=) echo "$1" >> optdef.sh;;
-		*=*)
-			echo "$me: use '-D symbol=val', not '-U symbol=val'." >&2
-			echo "$me: ignoring -U $1" >&2
-			;;
-		*) echo "$1='undef'" >> optdef.sh;;
-		esac
-		shift
-		;;
-	-A)
-	    shift
-	    xxx=''
-	    yyy="$1"
-	    zzz=''
-	    uuu=undef
-	    case "$yyy" in
-            *=*) zzz=`echo "$yyy"|sed 's!=.*!!'`
-                 case "$zzz" in
-                 *:*) zzz='' ;;
-                 *)   xxx=append
-                      zzz=" "`echo "$yyy"|sed 's!^[^=]*=!!'` 
-                      yyy=`echo "$yyy"|sed 's!=.*!!'` ;;
-                 esac
-                 ;;
-            esac
-            case "$xxx" in
-            '')  case "$yyy" in
-                 *:*) xxx=`echo "$yyy"|sed 's!:.*!!'`
-                      yyy=`echo "$yyy"|sed 's!^[^:]*:!!'`
-                      zzz=`echo "$yyy"|sed 's!^[^=]*=!!'`
-                      yyy=`echo "$yyy"|sed 's!=.*!!'` ;;
-                 *)   xxx=`echo "$yyy"|sed 's!:.*!!'`
-                      yyy=`echo "$yyy"|sed 's!^[^:]*:!!'` ;;
-                 esac
-                 ;;       
-            esac
-	    case "$xxx" in
-	    append)
-		echo "$yyy=\"\${$yyy}$zzz\""	>> posthint.sh ;;
-	    clear)
-		echo "$yyy=''"			>> posthint.sh ;;
-	    define)
-	        case "$zzz" in
-		'') zzz=define ;;
-		esac
-		echo "$yyy='$zzz'"		>> posthint.sh ;;
-	    eval)
-		echo "eval \"$yyy=$zzz\""	>> posthint.sh ;;
-	    prepend)
-		echo "$yyy=\"$zzz\${$yyy}\""	>> posthint.sh ;;
-	    undef)
-	        case "$zzz" in
-		'') zzz="$uuu" ;;
-		esac
-		echo "$yyy=$zzz"		>> posthint.sh ;;
-            *)  echo "$me: unknown -A command '$xxx', ignoring -A $1" >&2 ;;
-	    esac
-	    shift
-	    ;;
-	-V) echo "$me generated by metaconfig 3.0 PL70." >&2
-	    exit 0;;
+	arg="$1"
+	shift
+
+	echo "arg=$arg"
+	case "$arg" in
 	--) break;;
-	-*) echo "$me: unknown option $1" >&2; shift; error=true;;
-	*) break;;
+	-*);;
+	*)	echo "$me: unknown option: \"$arg\"" >&2
+		break;;
 	esac
+	
+	while :; do
+		case "$arg" in
+		-d*) 	fastread=yes;;
+		-e*) 	alldone=yes;;
+		-h*) 	error=true;;
+		-r*) 	reuseval=true;;
+		-s*) 	silent=true; realsilent=true;;
+		-E*) 	alldone=exit;;
+		-K*) 	knowitall=true;;
+		-O*) 	override=true;;
+		-S*) 	silent=true; extractsh=true;;
+		-V*)	echo "$me generated by metaconfig 3.0 PL70." >&2
+			exit 0;;
+
+		-f)
+			cd ..
+			if test -r "$1"; then
+				config_sh="$1"
+			else
+				echo "$me: cannot read config file $1." >&2
+			fi
+			cd UU
+			shift
+			;;
+
+		-D*)
+			case "$arg" in
+			-D)	param="$1"
+				shift
+				;;
+			*)	param="${arg#-?}"
+				;;
+			esac
+			arg=
+
+			symbol="${param%%=*}"
+			if [ X"$symbol" = X"$param" ]; then
+				value='define'
+			else
+				value="${param#*=}"
+				value="${value## }"
+			fi
+			case "$value" in
+			'') echo "$me: use '-U symbol=', not '-D symbol='." >&2
+			    echo "$me: ignoring -D $symbol" >&2
+			    ;;
+			*)  echo "$symbol=$value" | \
+				sed -e "s/'/'\"'\"'/g" -e "s/=\(.*\)/='\1'/" \
+				>> optdef.sh
+			    ;;
+			esac
+			;;
+
+		-U*)
+			case "$arg" in
+			-U)	param="$1"
+				shift
+				;;
+			*)	param="${arg#-?}"
+				;;
+			esac
+			arg=
+
+			symbol="${param%%=*}"
+			if [ X"$symbol" = X"$param" ]; then
+				value='undef'
+			else
+				value="${param#*=}"
+			fi
+			case "$value" in
+			''|undef)  echo "$symbol=$value" | \
+				sed -e "s/'/'\"'\"'/g" -e "s/=\(.*\)/='\1'/" \
+				>> optdef.sh
+			    ;;
+			*)  echo "$me: use '-D symbol=val', not '-U symbol=val'." >&2
+			    echo "$me: ignoring -U $symbol" >&2
+			    ;;
+			esac
+			;;
+
+		-A*)
+			case "$arg" in
+			-A)	param="$1"
+				shift
+				;;
+			*)	param="${arg#-?}"
+				;;
+			esac
+			arg=
+
+			xxx=''
+			yyy="$param"
+			zzz=''
+			uuu=undef
+			case "$yyy" in
+				*=*) zzz=`echo "$yyy"|sed 's!=.*!!'`
+				case "$zzz" in
+				*:*) zzz='' ;;
+				*)   xxx=append
+				     zzz=" "`echo "$yyy"|sed 's!^[^=]*=!!'` 
+				     yyy=`echo "$yyy"|sed 's!=.*!!'` ;;
+				esac
+				;;
+			esac
+			case "$xxx" in
+			'')  case "$yyy" in
+			     *:*) xxx=`echo "$yyy"|sed 's!:.*!!'`
+			     yyy=`echo "$yyy"|sed 's!^[^:]*:!!'`
+			     zzz=`echo "$yyy"|sed 's!^[^=]*=!!'`
+			     yyy=`echo "$yyy"|sed 's!=.*!!'` ;;
+			     *)   xxx=`echo "$yyy"|sed 's!:.*!!'`
+				  yyy=`echo "$yyy"|sed 's!^[^:]*:!!'` ;;
+			     esac
+			     ;;       
+			esac
+			case "$xxx" in
+			append)
+				echo "$yyy=\"\${$yyy}$zzz\"" >> posthint.sh ;;
+			clear)
+				echo "$yyy=''" >> posthint.sh ;;
+			define)
+				case "$zzz" in
+				'') zzz=define ;;
+				esac
+				echo "$yyy='$zzz'" >> posthint.sh ;;
+			eval)
+				echo "eval \"$yyy=$zzz\"" >> posthint.sh ;;
+			prepend)
+				echo "$yyy=\"$zzz\${$yyy}\"" >> posthint.sh ;;
+			undef)
+				case "$zzz" in
+				'') zzz="$uuu" ;;
+				esac
+				echo "$yyy=$zzz" >> posthint.sh ;;
+			*)  echo "$me: unknown -A command '$xxx', ignoring -A $param" >&2 ;;
+			esac
+			;;
+
+		*) 	echo "$me: unknown option: \"$arg\"" >&2
+			error=true
+			break
+			;;
+		esac
+		arg=${arg#-?}
+		arg=${arg:+-$arg}
+		if [ X"$arg" = X ]; then break; fi
+	done
 done
 
 case "$error" in
