Added signal trapping layer to be able to determine whether we are in signal handler or not. When dumping stack traces from critical points, allow symbolic traces by loading symbols provided we are not within a signal handler.

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -18,7 +18,7 @@
 
 # $Id$
 #
-# Generated on Wed Jan 12 17:40:13 CET 2011 [metaconfig 3.5-73]
+# Generated on Thu Jan 13 21:06:37 CET 2011 [metaconfig 3.5-74]
 
 cat >c1$$ <<EOF
 ARGGGHHHH!!!!!
@@ -552,6 +552,12 @@ prototype=''
 d_remotectrl=''
 remotectrl=''
 sh=''
+sig_count=''
+sig_name=''
+sig_name_init=''
+sig_num=''
+sig_num_init=''
+sig_size=''
 so=''
 sharpbang=''
 shsharp=''
@@ -686,7 +692,7 @@ case "$sh" in
 $me:  Fatal Error:  I can't find a Bourne Shell anywhere.  
 
 Usually it's in /bin/sh.  How did you even get this far?
-Please contact me (gtk-gnutella-developers) at gtk-gnutella-devel@lists.sourceforge.net and 
+Please contact me (gtk-gnutella developers) at gtk-gnutella-devel@lists.sourceforge.net and 
 we'll try to straighten this all out.
 EOM
 	exit 1
@@ -956,7 +962,7 @@ while test $# -gt 0; do
 	    esac
 	    shift
 	    ;;
-	-V) echo "$me generated by metaconfig 3.5-73." >&2
+	-V) echo "$me generated by metaconfig 3.5-74." >&2
 	    exit 0;;
 	--) break;;
 	-*) echo "$me: unknown option $1" >&2; shift; error=true;;
@@ -8582,6 +8588,261 @@ else
 fi
 $rm -f foo* bar* 
 
+: Trace out the files included by signal.h, then look for SIGxxx names.
+if [ "X$fieldn" = X ]; then
+	: Just make some guesses.  We check them later.
+	xxx='/usr/include/signal.h /usr/include/sys/signal.h'
+else
+	xxx=`echo '#include <signal.h>' |
+	$cppstdin $cppminus $cppflags 2>/dev/null |
+	$grep '^[ 	]*#.*include' | 
+	$awk "{print \\$$fieldn}" | $sed 's!"!!g' | \
+		$sed 's!\\\\\\\\!/!g' | $sort | $uniq`
+fi
+xxxfiles=''
+for xx in $xxx /dev/null ; do
+	$test -f "$xx" && xxxfiles="$xxxfiles $xx"
+done
+case "$xxxfiles" in
+'')	xxxfiles=`./findhdr signal.h` ;;
+esac
+xxx=`awk '
+$1 ~ /^#define$/ && $2 ~ /^SIG[A-Z0-9]*$/ && $2 !~ /SIGARRAYSIZE/ && $2 !~ /SIGSTKSIZE/ && $2 !~ /SIGSTKSZ/ && $3 !~ /void/ {
+	print substr($2, 4, 20)
+}
+$1 == "#" && $2 ~ /^define$/ && $3 ~ /^SIG[A-Z0-9]*$/ && $3 !~ /SIGARRAYSIZE/ && $4 !~ /void/ {
+	print substr($3, 4, 20)
+}' $xxxfiles`
+: Append some common names just in case the awk scan failed.
+xxx="$xxx ABRT ALRM BUS CANCEL CHLD CLD CONT DIL EMT FPE"
+xxx="$xxx FREEZE HUP ILL INT IO IOT KILL LOST LWP PHONE"
+xxx="$xxx PIPE POLL PROF PWR QUIT RTMAX RTMIN SEGV STKFLT STOP"
+xxx="$xxx SYS TERM THAW TRAP TSTP TTIN TTOU URG USR1 USR2"
+xxx="$xxx USR3 USR4 VTALRM WAITING WINCH WIND WINDOW XCPU XFSZ"
+
+: generate a few handy files for later
+$cat > signal.c <<'EOCP'
+#include <sys/types.h>
+#include <signal.h>
+#include <stdio.h>
+int main() {
+
+/* Strange style to avoid deeply-nested #if/#else/#endif */
+#ifndef NSIG
+#  ifdef _NSIG
+#    define NSIG (_NSIG)
+#  endif
+#endif
+
+#ifndef NSIG
+#  ifdef SIGMAX
+#    define NSIG (SIGMAX+1)
+#  endif
+#endif
+
+#ifndef NSIG
+#  ifdef SIG_MAX
+#    define NSIG (SIG_MAX+1)
+#  endif
+#endif
+
+#ifndef NSIG
+#  ifdef MAXSIG
+#    define NSIG (MAXSIG+1)
+#  endif
+#endif
+
+#ifndef NSIG
+#  ifdef MAX_SIG
+#    define NSIG (MAX_SIG+1)
+#  endif
+#endif
+
+#ifndef NSIG
+#  ifdef SIGARRAYSIZE
+#    define NSIG (SIGARRAYSIZE+1) /* Not sure of the +1 */
+#  endif
+#endif
+
+#ifndef NSIG
+#  ifdef _sys_nsig
+#    define NSIG (_sys_nsig) /* Solaris 2.5 */
+#  endif
+#endif
+
+/* Default to some arbitrary number that's big enough to get most
+   of the common signals.
+*/
+#ifndef NSIG
+#    define NSIG 50
+#endif
+
+printf("NSIG %d\n", NSIG);
+
+#ifndef JUST_NSIG
+
+EOCP
+
+echo $xxx | $tr ' ' $trnl | $sort | $uniq | $awk '
+{
+	printf "#ifdef SIG"; printf $1; printf "\n"
+	printf "printf(\""; printf $1; printf " %%d\\n\",SIG";
+	printf $1; printf ");\n"
+	printf "#endif\n"
+}
+END {
+	printf "#endif /* JUST_NSIG */\n";
+	printf "return 0;\n}\n";
+}
+' >>signal.c
+$cat >signal.awk <<'EOP'
+BEGIN { ndups = 0 }
+$1 ~ /^NSIG$/ { nsig = $2 }
+($1 !~ /^NSIG$/) && (NF == 2) {
+    if ($2 > maxsig) { maxsig = $2 }
+    if (sig_name[$2]) {
+	dup_name[ndups] = $1
+	dup_num[ndups] = $2
+	ndups++ 
+    }
+    else {
+	sig_name[$2] = $1
+	sig_num[$2] = $2
+    }
+}
+END { 
+    if (nsig == 0) {
+    	nsig = maxsig + 1
+    }
+    printf("NSIG %d\n", nsig);
+    for (n = 1; n < nsig; n++) {
+ 	if (sig_name[n]) {
+ 	    printf("%s %d\n", sig_name[n], sig_num[n])
+	}
+ 	else {
+ 	    printf("NUM%d %d\n", n, n) 
+ 	}
+    }
+    for (n = 0; n < ndups; n++) {
+ 	printf("%s %d\n", dup_name[n], dup_num[n])
+    }
+}
+EOP
+$cat >signal_cmd <<EOS
+$startsh
+if $test -s signal.lst; then
+    echo "Using your existing signal.lst file"
+	exit 0
+fi
+xxx="$xxx"
+EOS
+$cat >>signal_cmd <<'EOS'
+
+set signal
+if eval $compile_ok; then
+	$run ./signal$_exe | ($sort -n -k 2 2>/dev/null || $sort -n +1) | \
+		$uniq | $awk -f signal.awk >signal.lst
+else
+	echo "(I can't seem be able to compile the whole test program)" >&4
+	echo "(I'll try it in little pieces.)" >&4
+	set signal -DJUST_NSIG
+	if eval $compile_ok; then
+		$run ./signal$_exe > signal.nsg
+		$cat signal.nsg
+	else
+		echo "I can't seem to figure out how many signals you have." >&4
+		echo "Guessing 50." >&4
+		echo 'NSIG 50' > signal.nsg
+	fi
+	: Now look at all the signal names, one at a time.
+	for xx in `echo $xxx | $tr ' ' $trnl | $sort | $uniq`; do
+		$cat > signal.c <<EOCP
+#include <sys/types.h>
+#include <signal.h>
+#include <stdio.h>
+int main() {
+printf("$xx %d\n", SIG${xx});
+return 0;
+}
+EOCP
+		set signal
+		if eval $compile; then
+			echo "SIG${xx} found."
+			$run ./signal$_exe  >> signal.ls1
+		else
+			echo "SIG${xx} NOT found."
+		fi
+	done
+	if $test -s signal.ls1; then
+		$cat signal.nsg signal.ls1 |
+			$sort -n | $uniq | $awk -f signal.awk >signal.lst
+	fi
+
+fi
+if $test -s signal.lst; then
+	:
+else
+	echo "(AAK! I can't compile the test programs -- Guessing)" >&4
+	echo 'kill -l' >signal
+	set X `csh -f <signal`
+	$rm -f signal
+	shift
+	case $# in
+	0) set HUP INT QUIT ILL TRAP ABRT EMT FPE KILL BUS SEGV SYS PIPE ALRM TERM;;
+	esac
+	echo $@ | $tr ' ' $trnl | \
+ 	    $awk '{ printf "%s %d\n", $1, ++s; }
+ 		  END { printf "NSIG %d\n", ++s }' >signal.lst
+fi
+$rm -f signal.c signal$_exe signal$_o signal.nsg signal.ls1
+EOS
+chmod a+x signal_cmd
+$eunicefix signal_cmd
+
+: generate list of signal names
+echo " "
+case "$sig_name_init" in
+'') doinit=yes ;;
+*)  case "$sig_num_init" in
+    ''|*,*) doinit=yes ;;
+    esac ;;
+esac
+case "$doinit" in
+yes)
+	echo "Generating a list of signal names and numbers..." >&4
+	. ./signal_cmd
+ 	sig_count=`$awk '/^NSIG/ { printf "%d", $2 }' signal.lst`
+ 	sig_name=`$awk 'BEGIN { printf "ZERO " }
+ 			!/^NSIG/ { printf "%s ", $1 }' signal.lst`
+ 	sig_num=`$awk  'BEGIN { printf "0 " }
+ 			!/^NSIG/ { printf "%d ", $2 }' signal.lst`
+ 	sig_name_init=`$awk 'BEGIN	{ printf "\"ZERO\", " }
+ 			     !/^NSIG/	{ printf "\"%s\", ", $1 }
+ 			     END	{ printf "0\n" }' signal.lst`
+ 	sig_num_init=`$awk  'BEGIN	{ printf "0, " }
+ 			     !/^NSIG/	{ printf "%d, ", $2}
+ 			     END	{ printf "0\n"}' signal.lst`
+	;;
+esac
+echo "The following $sig_count signals are available:"
+echo " "
+echo $sig_name | $awk \
+'BEGIN { linelen = 0 }
+{
+	for (i = 1; i <= NF; i++) {
+		name = "SIG" $i " "
+		linelen = linelen + length(name)
+		if (linelen > 70) {
+			printf "\n"
+			linelen = length(name)
+		}
+		printf "%s", name
+	}
+	printf "\n"
+}'
+sig_size=`echo $sig_name | awk '{print NF}'`
+$rm -f signal signal.c signal.awk signal.lst signal_cmd 
+
 : check for void type
 echo " "
 echo "Checking to see how well your C compiler groks the void type..." >&4
@@ -9850,6 +10111,12 @@ sh='$sh'
 shar='$shar'
 sharpbang='$sharpbang'
 shsharp='$shsharp'
+sig_count='$sig_count'
+sig_name='$sig_name'
+sig_name_init='$sig_name_init'
+sig_num='$sig_num'
+sig_num_init='$sig_num_init'
+sig_size='$sig_size'
 signal_t='$signal_t'
 sleep='$sleep'
 smail='$smail'
