Regenerated.

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -18,7 +18,7 @@
 
 # $Id$
 #
-# Generated on Sat Dec 11 19:33:17 CET 2010 [metaconfig 3.5-]
+# Generated on Sun Dec 12 00:47:25 CET 2010 [metaconfig 3.5-57]
 
 cat >c1$$ <<EOF
 ARGGGHHHH!!!!!
@@ -388,6 +388,7 @@ d_dbus=''
 dbuscflags=''
 dbusconfig=''
 dbusldflags=''
+ebcdic=''
 d_enablenls=''
 enablenls=''
 cppfilter=''
@@ -432,6 +433,7 @@ i_libcharset=''
 i_libintl=''
 i_limits=''
 i_math=''
+i_mswsock=''
 i_netdb=''
 i_netif=''
 i_niin=''
@@ -475,6 +477,7 @@ i_stdarg=''
 i_varargs=''
 i_varhdr=''
 i_winsock2=''
+i_ws2tcpip=''
 i_zlib=''
 install=''
 installdir=''
@@ -940,7 +943,7 @@ while test $# -gt 0; do
 	    esac
 	    shift
 	    ;;
-	-V) echo "$me generated by metaconfig 3.5-." >&2
+	-V) echo "$me generated by metaconfig 3.5-57." >&2
 	    exit 0;;
 	--) break;;
 	-*) echo "$me: unknown option $1" >&2; shift; error=true;;
@@ -4625,18 +4628,48 @@ eval $inhdr
 set netdb.h i_netdb
 eval $inhdr
 
+: see if this is a sys/socket.h system
+set sys/socket.h i_syssock
+eval $inhdr
+
+: see if this is a winsock2.h system
+set winsock2.h i_winsock2
+eval $inhdr
+
+: see if this is a ws2tcpip.h system
+set ws2tcpip.h i_ws2tcpip
+eval $inhdr
+
+: see if this is a netinet/in.h or sys/in.h system
+set netinet/in.h i_niin sys/in.h i_sysin
+eval $inhdr
+
 : can we use getaddrinfo?
 $cat >try.c <<EOC
-#include <sys/types.h>
-#include <sys/socket.h>
-#include <netinet/in.h>
+#$i_syssock I_SYS_SOCKET
+#$i_winsock2 I_WINSOCK2
+#$i_ws2tcpip I_WS2TCPIP
+#$i_niin I_NETINET_IN
 #$i_arpainet I_ARPA_INET
+#$i_netdb I_NETDB
+#include <sys/types.h>
+#ifdef I_SYS_SOCKET
+#include <sys/socket.h>
+#endif
+#ifdef I_NETINET_IN
+#include <netinet/in.h>
+#endif
 #ifdef I_ARPA_INET
 #include <arpa/inet.h>
 #endif
-#$i_netdb I_NETDB
 #ifdef I_NETDB
 #include <netdb.h>
+#endif
+#ifdef I_WINSOCK2
+#include <Winsock2.h>
+#endif
+#ifdef I_WS2TCPIP
+#include <Ws2tcpip.h>
 #endif
 int main(void)
 {
@@ -4663,7 +4696,7 @@ int main(void)
 }
 EOC
 cyn=getaddrinfo
-set d_getaddrinfo
+set d_getaddrinfo '-lWs2_32'
 eval $trylink
 
 : can we use geteuid?
@@ -5559,10 +5592,6 @@ cyn=hstrerror
 set d_hstrerror 
 eval $trylink
 
-: see if this is a netinet/in.h or sys/in.h system
-set netinet/in.h i_niin sys/in.h i_sysin
-eval $inhdr
-
 : see if this is a netinet/ip.h system
 set netinet/ip.h i_niip
 eval $inhdr
@@ -5575,11 +5604,23 @@ case "$i_niin" in
 *)
 	case "$i_sysin" in
 	"$define") inh=sys/in.h;;
+	*)
+		case "$i_ws2tcpip" in
+		"$define") inh=Ws2tcpip.h;;
+		esac
+		;;
 	esac
 	;;
 esac
 $cat >iptos <<EOM
+#$i_syssock I_SYS_SOCKET
+#$i_winsock2 I_WINSOCK2
+#ifdef I_SYS_SOCKET
 #include <sys/socket.h>
+#endif
+#ifdef I_WINSOCK2
+#include <Winsock2.h>
+#endif
 #include <$inh>
 #if defined(IP_TOS) && defined(IPTOS_LOWDELAY) && defined(IPTOS_THROUGHPUT)
 YES
@@ -5592,12 +5633,15 @@ if $contains 'YES' iptos.h >/dev/null 2>&1; then
 	echo "You have IP TOS support in <$inh>." >&4
 elif $test "x$i_niip" = "x$define"; then
 	$cat >iptos <<EOM
-	#include <sys/socket.h>
-	#include <$inh>
-	#include <netinet/ip.h>
-	#if defined(IP_TOS) && defined(IPTOS_LOWDELAY) && defined(IPTOS_THROUGHPUT)
-	YES
-	#endif
+#$i_syssock I_SYS_SOCKET
+#ifdef I_SYS_SOCKET
+#include <sys/socket.h>
+#endif
+#include <$inh>
+#include <netinet/ip.h>
+#if defined(IP_TOS) && defined(IPTOS_LOWDELAY) && defined(IPTOS_THROUGHPUT)
+YES
+#endif
 EOM
 	$cppstdin $cppflags $cppminus <iptos >iptos.h 2>/dev/null
 	if $contains 'YES' iptos.h >/dev/null 2>&1; then
@@ -5618,14 +5662,21 @@ case "$d_ipv6" in
 ;;
 *)
 	$cat >try.c <<EOC
-#include <sys/types.h>
-#include <sys/socket.h>
-#include <netinet/in.h>
+#$i_syssock I_SYS_SOCKET
+#$i_winsock2 I_WINSOCK2
+#$i_niin I_NETINET_IN
 #$i_arpainet I_ARPA_INET
+#$i_netdb I_NETDB
+#include <sys/types.h>
+#ifdef I_SYS_SOCKET
+#include <sys/socket.h>
+#endif
+#ifdef I_NETINET_IN
+#include <netinet/in.h>
+#endif
 #ifdef I_ARPA_INET
 #include <arpa/inet.h>
 #endif
-#$i_netdb I_NETDB
 #ifdef I_NETDB
 #include <netdb.h>
 #endif
@@ -5926,10 +5977,36 @@ cyn=mmap
 set d_mmap
 eval $trylink
 
+: see if sys/types.h has to be included
+set sys/types.h i_systypes
+eval $inhdr
+
+: see if sys/select.h has to be included
+set sys/select.h i_sysselct
+eval $inhdr
+
+: see if this is a mswsock.h system
+set mswsock.h i_mswsock
+eval $inhdr
+
 : check for msg_flags in struct msghdr
 $cat >try.c <<EOC
+#$i_systypes I_SYS_TYPES
+#$i_sysselct I_SYS_SELECT
+#$i_winsock2 I_WINSOCK2
+#$i_mswsock I_MSWSOCK
+#ifdef I_SYS_TYPES
 #include <sys/types.h>
+#endif
+#ifdef I_SYS_SOCKET
 #include <sys/socket.h>
+#endif
+#ifdef I_WINSOCK2
+#include <Winsock2.h>
+#endif
+#ifdef I_MSWSOCK
+#include <Mswsock.h>
+#endif
 int main(void)
 {
 	struct msghdr msg;
@@ -6243,18 +6320,6 @@ cyn="whether SA_INTERRUPT is available in <signal.h>"
 set d_sa_interrupt
 eval $trylink
 
-: see if sys/types.h has to be included
-set sys/types.h i_systypes
-eval $inhdr
-
-: see if sys/select.h has to be included
-set sys/select.h i_sysselct
-eval $inhdr
-
-: see if this is a winsock2.h system
-set winsock2.h i_winsock2
-eval $inhdr
-
 : see if select exists
 $cat >try.c <<EOC
 #$i_unistd I_UNISTD
@@ -6283,7 +6348,7 @@ int main(void)
 }
 EOC
 cyn=select
-set d_select '-lWs_32'
+set d_select '-lWs2_32'
 eval $trylink
 
 : see if sendfile exists
@@ -6388,12 +6453,22 @@ $rm -f set.c set
 
 : does struct sockaddr_in has sin_len
 $cat >try.c <<EOC
-#include <sys/types.h>
-#include <sys/socket.h>
-#include <netinet/in.h>
+#$i_syssock I_SYS_SOCKET
+#$i_niin I_NETINET_IN
+#$i_winsock2 I_WINSOCK2
 #$i_arpainet I_ARPA_INET
+#include <sys/types.h>
+#ifdef I_SYS_SOCKET
+#include <sys/socket.h>
+#endif
+#ifdef I_NETINET_IN
+#include <netinet/in.h>
+#endif
 #ifdef I_ARPA_INET
 #include <arpa/inet.h>
+#endif
+#ifdef I_WINSOCK2
+#include <Winsock2.h>
 #endif
 int main(void)
 {
@@ -7401,6 +7476,33 @@ EOCP
 	;;
 esac
 $rm -f try try.* .out core head.c mtry
+
+: look whether system uses EBCDIC
+echo " "
+echo "Determining whether or not we are on an EBCDIC system..." >&4
+$cat >try.c <<'EOM'
+int main()
+{
+	if ('M'==0xd4) return 0;
+	return 1;
+}
+EOM
+val=$undef
+set try
+if eval $compile_ok; then
+	if $run ./try; then
+		echo "You seem to speak EBCDIC." >&4
+		val="$define"
+	else
+		echo "Nope, no EBCDIC, probably ASCII or some ISO Latin. Or UTF-8." >&4
+	fi
+else
+	echo "I'm unable to compile the test program." >&4
+	echo "I'll assume ASCII or some ISO Latin. Or UTF8." >&4
+fi
+$rm -f try try.*
+set ebcdic
+eval $setvar
 
 : derive which glade to use based on the configured GTK+
 echo " "
@@ -8636,10 +8738,6 @@ esac
 set sys/sendfile.h i_syssendfile
 eval $inhdr
 
-: see if this is a sys/socket.h system
-set sys/socket.h i_syssock
-eval $inhdr
-
 : see if this is a sys/statvfs system
 set sys/statvfs.h i_sysstatvfs
 eval $inhdr
@@ -9275,6 +9373,7 @@ dbusldflags='$dbusldflags'
 defvoidused='$defvoidused'
 direntrytype='$direntrytype'
 eagain='$eagain'
+ebcdic='$ebcdic'
 echo='$echo'
 egrep='$egrep'
 emacs='$emacs'
@@ -9327,6 +9426,7 @@ i_libcharset='$i_libcharset'
 i_libintl='$i_libintl'
 i_limits='$i_limits'
 i_math='$i_math'
+i_mswsock='$i_mswsock'
 i_netdb='$i_netdb'
 i_netif='$i_netif'
 i_niin='$i_niin'
@@ -9362,6 +9462,7 @@ i_unistd='$i_unistd'
 i_varargs='$i_varargs'
 i_varhdr='$i_varhdr'
 i_winsock2='$i_winsock2'
+i_ws2tcpip='$i_ws2tcpip'
 i_zlib='$i_zlib'
 incpath='$incpath'
 inews='$inews'
