Regenerated Configure. Fixed MANIFEST, removing files not committed yet. Remove poll() defined from mingw32.h Regenerated src/lib/Makefile.SH.

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -18,7 +18,7 @@
 
 # $Id$
 #
-# Generated on Sun Dec 12 13:14:52 CET 2010 [metaconfig 3.5-59]
+# Generated on Sun Dec 12 13:36:16 CET 2010 [metaconfig 3.5-57]
 
 cat >c1$$ <<EOF
 ARGGGHHHH!!!!!
@@ -389,6 +389,7 @@ d_dbus=''
 dbuscflags=''
 dbusconfig=''
 dbusldflags=''
+ebcdic=''
 d_enablenls=''
 enablenls=''
 cppfilter=''
@@ -943,7 +944,7 @@ while test $# -gt 0; do
 	    esac
 	    shift
 	    ;;
-	-V) echo "$me generated by metaconfig 3.5-59." >&2
+	-V) echo "$me generated by metaconfig 3.5-57." >&2
 	    exit 0;;
 	--) break;;
 	-*) echo "$me: unknown option $1" >&2; shift; error=true;;
@@ -7544,6 +7545,33 @@ EOCP
 esac
 $rm -f try try.* .out core head.c mtry
 
+: look whether system uses EBCDIC
+echo " "
+echo "Determining whether or not we are on an EBCDIC system..." >&4
+$cat >try.c <<'EOM'
+int main()
+{
+	if ('M'==0xd4) return 0;
+	return 1;
+}
+EOM
+val=$undef
+set try
+if eval $compile_ok; then
+	if $run ./try; then
+		echo "You seem to speak EBCDIC." >&4
+		val="$define"
+	else
+		echo "Nope, no EBCDIC, probably ASCII or some ISO Latin. Or UTF-8." >&4
+	fi
+else
+	echo "I'm unable to compile the test program." >&4
+	echo "I'll assume ASCII or some ISO Latin. Or UTF8." >&4
+fi
+$rm -f try try.*
+set ebcdic
+eval $setvar
+
 : derive which glade to use based on the configured GTK+
 echo " "
 case "$gtkversion" in
@@ -9426,6 +9454,7 @@ dbusldflags='$dbusldflags'
 defvoidused='$defvoidused'
 direntrytype='$direntrytype'
 eagain='$eagain'
+ebcdic='$ebcdic'
 echo='$echo'
 egrep='$egrep'
 emacs='$emacs'
